services:
  web:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_PASSWORD: ${DB_PASSWORD}
      DB_HOST: mssql_server
      SEED_ADMIN_PASSWORD: ${SEED_ADMIN_PASSWORD}
      SEED_DEMO_PASSWORD: ${SEED_DEMO_PASSWORD}
    networks:
      - myapp-network

networks:
  myapp-network:
    external: true
